import type { FounderProfile, FounderBenchmarkResult } from "./types";
import { avgRecentGrowth, momGrowthRates } from "./trajectory";
import { calcHealthScore, calcFundraisingReadiness } from "./scorecard";

/**
 * Generate a markdown investor update from founder profile and benchmark data.
 */
export function generateInvestorUpdate(
  profile: FounderProfile,
  benchmarks: FounderBenchmarkResult[]
): string {
  const { company, snapshots } = profile;
  const sorted = [...snapshots].sort((a, b) => a.month.localeCompare(b.month));
  const latest = sorted[sorted.length - 1];
  const previous = sorted.length >= 2 ? sorted[sorted.length - 2] : null;
  const health = calcHealthScore(snapshots);
  const readiness = calcFundraisingReadiness(snapshots);
  const avgGrowth = avgRecentGrowth(snapshots, 3);
  const ltvCac = latest.cac > 0 ? (latest.ltv / latest.cac).toFixed(1) : "N/A";
  const rates = momGrowthRates(snapshots);
  const latestGrowth = rates.length > 0 ? rates[rates.length - 1].growth : 0;

  const mrrDelta = previous
    ? ((latest.mrr - previous.mrr) / previous.mrr * 100).toFixed(1)
    : "N/A";
  const customerDelta = previous
    ? ((latest.customers - previous.customers) / previous.customers * 100).toFixed(1)
    : "N/A";

  // Format currency
  const fmt = (v: number) => {
    if (v >= 1_000_000) return `$${(v / 1_000_000).toFixed(1)}M`;
    if (v >= 1_000) return `$${(v / 1_000).toFixed(0)}K`;
    return `$${v}`;
  };

  // Find best benchmark positions
  const topBenchmarks = benchmarks
    .filter((b) => b.percentile >= 60)
    .sort((a, b) => b.percentile - a.percentile)
    .slice(0, 3);

  const weakBenchmarks = benchmarks
    .filter((b) => b.percentile < 40)
    .sort((a, b) => a.percentile - b.percentile)
    .slice(0, 2);

  let md = `# ${company.name} — Investor Update\n\n`;
  md += `**${latest.month}** · ${company.sector} · ${company.batch} · ${company.stage}\n\n`;
  md += `---\n\n`;

  // Period Summary
  md += `## Summary\n\n`;
  md += `${company.name} ${latestGrowth >= 10 ? "had a strong month" : latestGrowth >= 5 ? "continued steady progress" : "navigated a challenging period"} `;
  md += `with MRR reaching **${fmt(latest.mrr)}** (${mrrDelta !== "N/A" ? `${Number(mrrDelta) >= 0 ? "+" : ""}${mrrDelta}% MoM` : "first month"}).\n\n`;

  // Key Metrics
  md += `## Key Metrics\n\n`;
  md += `| Metric | Value | MoM Change |\n`;
  md += `|--------|-------|------------|\n`;
  md += `| MRR | ${fmt(latest.mrr)} | ${mrrDelta !== "N/A" ? `${Number(mrrDelta) >= 0 ? "+" : ""}${mrrDelta}%` : "—"} |\n`;
  md += `| ARR | ${fmt(latest.mrr * 12)} | — |\n`;
  md += `| Customers | ${latest.customers} | ${customerDelta !== "N/A" ? `${Number(customerDelta) >= 0 ? "+" : ""}${customerDelta}%` : "—"} |\n`;
  md += `| Churn Rate | ${latest.churnRate.toFixed(1)}% | — |\n`;
  md += `| LTV:CAC | ${ltvCac}x | — |\n`;
  md += `| Burn Rate | ${fmt(latest.burn)} | — |\n`;
  md += `| Runway | ${latest.runway.toFixed(0)} months | — |\n`;
  md += `| NPS | ${latest.nps} | — |\n`;
  md += `| Avg MoM Growth (3mo) | ${avgGrowth.toFixed(1)}% | — |\n\n`;

  // Health & Readiness
  md += `## Overall Health\n\n`;
  md += `- **Health Score:** ${health.overall}/100\n`;
  md += `- **Fundraising Readiness:** ${readiness.label} (${readiness.score}%)\n\n`;

  // Benchmarks
  if (topBenchmarks.length > 0) {
    md += `## Highlights\n\n`;
    for (const b of topBenchmarks) {
      md += `- **${b.label}**: Top ${100 - b.percentile}% among ${company.batch} cohort (P${b.percentile})\n`;
    }
    md += `\n`;
  }

  if (weakBenchmarks.length > 0) {
    md += `## Areas for Improvement\n\n`;
    for (const b of weakBenchmarks) {
      md += `- **${b.label}**: P${b.percentile} — cohort median is ${b.unit === "$" ? fmt(b.cohortMedian) : `${b.cohortMedian}${b.unit}`}\n`;
    }
    md += `\n`;
  }

  // Readiness signals
  md += `## Fundraising Readiness Checklist\n\n`;
  for (const s of readiness.signals) {
    md += `- ${s.met ? "✅" : "⬜"} ${s.label}: ${s.current} (target: ${s.target})\n`;
  }
  md += `\n`;

  md += `---\n\n`;
  md += `*Generated by VC OS · ${new Date().toISOString().split("T")[0]}*\n`;

  return md;
}
